### ISSUE TITLE
麻烦问下大佬

### ISSUE THREAD

**Issue by ID114514** [pcrbot/erinilis-modules#100]
抽卡记录插件上传文件后，一直卡在 “检测到卡池记录文件.正在导入数据” 这个状态，是什么原因啊

**Comment by yuyumoko** [comment]
有报错日志吗

**Comment by ID114514** [comment]
> 有报错日志吗

这个报错日志文件一般是保存在哪个文件夹里的呀？

**Comment by yuyumoko** [comment]
就在启动hoshino那个窗口

**Comment by ID114514** [comment]
> 就在启动hoshino那个窗口



> 就在启动hoshino那个窗口

[2021-12-08 12:33:01,304 nonebot] INFO: Notice: <Event, {'file': {'busid': 102, 'id': '/ecd9faaa-57df-11ec-8ba5-5452007bd6c0', 'name': 'gacha-list-174876912.json', 'size': 106214, 'url': 'http://109.244.227.121/ftn_handler/a2b4b709f0cd432494ad124fe698fe4cc4f432e3bb319650caa0b00dd458a0f31443d67524c30ba91f083377d36ed1d33edc9c9fb46c9cd19d4371b69446f52c/?fname=2f65636439666161612d353764662d313165632d386261352d353435323030376264366330'}, 'group_id': 791641964, 'notice_type': 'group_upload', 'post_type': 'notice', 'self_id': 3073185748, 'time': 1638937981, 'user_id': 1767041706}>
[2021-12-08 12:33:01,696 nonebot] ERROR: An exception occurred while handling event notice.group_upload:
[2021-12-08 12:33:01,697 nonebot] ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\notice_request.py", line 109, in handle_notice_or_request
    await EventManager.bus.emit(ev_name, session)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\bus.py", line 60, in emit
    results += await run_async_funcs(self._subscribers[event], *args,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\utils.py", line 40, in run_async_funcs
    results += await asyncio.gather(*coros)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot\hoshino\service.py", line 395, in wrapper
    return await func(session)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot\hoshino\modules\genshingachalog\__init__.py", line 95, in main
    json_data = await res.json(object_hook=util.Dict)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot\hoshino\aiorequests.py", line 57, in json
    return await run_sync_func(self.raw_response.json, **kwargs)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot\hoshino\aiorequests.py", line 10, in run_sync_func
    return await asyncio.get_event_loop().run_in_executor(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

是这一串吗？

**Comment by yuyumoko** [comment]
你上传错文件了吧.. 应该是json那个文件`gacha-list-UID.json`
我看你那个文件excel的文件 , 然后改个名? 那当然不行

**Comment by ID114514** [comment]
> 你上传错文件了吧.. 应该是json那个文件`gacha-list-UID.json` 我看你那个文件excel的文件 , 然后改个名? 那当然不行

原来是要用xlsx转成json然后上传的吗

**Comment by yuyumoko** [comment]
> > 你上传错文件了吧.. 应该是json那个文件`gacha-list-UID.json` 我看你那个文件excel的文件 , 然后改个名? 那当然不行
> 
> 原来是要用xlsx转成json然后上传的吗

不是 , 是其他软件生成的  不是转换的, 一般和xlsx一起生成的 但一定不是xlsx

**Comment by ID114514** [comment]
> > > 你上传错文件了吧.. 应该是json那个文件`gacha-list-UID.json` 我看你那个文件excel的文件 , 然后改个名? 那当然不行
> > 
> > 
> > 原来是要用xlsx转成json然后上传的吗
> 
> 不是 , 是其他软件生成的 不是转换的, 一般和xlsx一起生成的 但一定不是xlsx

...我用的刻晴牛杂铺，只给我导出了个xlsx，大佬有什么导出json的工具吗

**Comment by yuyumoko** [comment]
> > > > 你上传错文件了吧.. 应该是json那个文件`gacha-list-UID.json` 我看你那个文件excel的文件 , 然后改个名? 那当然不行
> > > 
> > > 
> > > 原来是要用xlsx转成json然后上传的吗
> > 
> > 
> > 不是 , 是其他软件生成的 不是转换的, 一般和xlsx一起生成的 但一定不是xlsx
> 
> ...我用的刻晴牛杂铺，只给我导出了个xlsx，大佬有什么导出json的工具吗

不太清楚 , 就别人告诉我有这个东西 我就支持一下的

**Comment by ID114514** [comment]
> > > > > 你上传错文件了吧.. 应该是json那个文件`gacha-list-UID.json` 我看你那个文件excel的文件 , 然后改个名? 那当然不行
> > > > 
> > > > 
> > > > 原来是要用xlsx转成json然后上传的吗
> > > 
> > > 
> > > 不是 , 是其他软件生成的 不是转换的, 一般和xlsx一起生成的 但一定不是xlsx
> > 
> > 
> > ...我用的刻晴牛杂铺，只给我导出了个xlsx，大佬有什么导出json的工具吗
> 
> 不太清楚 , 就别人告诉我有这个东西 我就支持一下的

我尝试了下json，然后...还是报错

**Comment by yuyumoko** [comment]
> > > > > > 你上传错文件了吧.. 应该是json那个文件`gacha-list-UID.json` 我看你那个文件excel的文件 , 然后改个名? 那当然不行
> > > > > 
> > > > > 
> > > > > 原来是要用xlsx转成json然后上传的吗
> > > > 
> > > > 
> > > > 不是 , 是其他软件生成的 不是转换的, 一般和xlsx一起生成的 但一定不是xlsx
> > > 
> > > 
> > > ...我用的刻晴牛杂铺，只给我导出了个xlsx，大佬有什么导出json的工具吗
> > 
> > 
> > 不太清楚 , 就别人告诉我有这个东西 我就支持一下的
> 
> 我尝试了下json，然后...还是报错

看看报错

**Comment by ID114514** [comment]
> > > > > > > 你上传错文件了吧.. 应该是json那个文件`gacha-list-UID.json` 我看你那个文件excel的文件 , 然后改个名? 那当然不行
> > > > > > 
> > > > > > 
> > > > > > 原来是要用xlsx转成json然后上传的吗
> > > > > 
> > > > > 
> > > > > 不是 , 是其他软件生成的 不是转换的, 一般和xlsx一起生成的 但一定不是xlsx
> > > > 
> > > > 
> > > > ...我用的刻晴牛杂铺，只给我导出了个xlsx，大佬有什么导出json的工具吗
> > > 
> > > 
> > > 不太清楚 , 就别人告诉我有这个东西 我就支持一下的
> > 
> > 
> > 我尝试了下json，然后...还是报错
> 
> 看看报错

[2021-12-08 12:46:38,683 nonebot] INFO: Notice: <Event, {'file': {'busid': 102, 'id': '/d4028c98-57e1-11ec-8723-5452007b7f04', 'name': 'gacha-list-174876912.json', 'size': 434650, 'url': 'http://109.244.227.105/ftn_handler/664fc3518851062d6de6a729cb9a534cb2c1f6d56aa9964ca23a76093751ec2ed66c58757941023caec511cadf42bd8739a62663b9671e5aecafcbbe7651b5c6/?fname=2f64343032386339382d353765312d313165632d383732332d353435323030376237663034'}, 'group_id': 791641964, 'notice_type': 'group_upload', 'post_type': 'notice', 'self_id': 3073185748, 'time': 1638938798, 'user_id': 1767041706}>
[2021-12-08 12:46:39,117 nonebot] ERROR: An exception occurred while handling event notice.group_upload:
[2021-12-08 12:46:39,117 nonebot] ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\notice_request.py", line 109, in handle_notice_or_request
    await EventManager.bus.emit(ev_name, session)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\bus.py", line 60, in emit
    results += await run_async_funcs(self._subscribers[event], *args,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\utils.py", line 40, in run_async_funcs
    results += await asyncio.gather(*coros)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot\hoshino\service.py", line 395, in wrapper
    return await func(session)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master\HoshinoBot\hoshino\modules\genshingachalog\__init__.py", line 97, in main
    gacha_data = sum(json_data.result, [])
TypeError: 'NoneType' object is not iterable

**Comment by yuyumoko** [comment]
还行  不兼容

**Comment by ID114514** [comment]
> 还行 不兼容

能解决吗，我应该如何解决呢

**Comment by yuyumoko** [comment]
> > 还行 不兼容
> 
> 能解决吗，我应该如何解决呢

比较麻烦 暂时寄了 这个打算重写的

**Comment by ID114514** [comment]
> > > 还行 不兼容
> > 
> > 
> > 能解决吗，我应该如何解决呢
> 
> 比较麻烦 暂时寄了 这个打算重写的

好吧，期待重制版了

**Comment by ID114514** [comment]
汗，刚才不知道怎么的显示导入成功了，使用命令“原神卡池统计”然后显示“尚未获取过卡池记录,请重新绑定刷新数据”，再次上传文件又显示'bool' object has no attribute 'list'，晕了

**Comment by yuyumoko** [comment]
有详细的报错吗

**Comment by ID114514** [comment]
> 有详细的报错吗

[2021-12-08 13:29:14,574 nonebot] INFO: Notice: <Event, {'file': {'busid': 102, 'id': '/c7731d0c-57e7-11ec-b240-5452007bdaa4', 'name': 'gacha-list-174876912.json', 'size': 117670, 'url': 'http://109.244.227.121/ftn_handler/345908bc8eb3eb5a48eb9b8284acfe556f7ebe1c06f5d1938ccf8ddc23f093754f315cb44cabae60b2c6312173a6b7bfaeb5f5ea3f8d526e81d10d4bf240d24d/?fname=2f63373733316430632d353765372d313165632d623234302d353435323030376264616134'}, 'group_id': 791641964, 'notice_type': 'group_upload', 'post_type': 'notice', 'self_id': 3073185748, 'time': 1638941354, 'user_id': 1767041706}>

**Comment by yuyumoko** [comment]
很好 json格式问题

**Comment by yuyumoko** [comment]
麻了 .. 奇怪的格式增加了!

**Comment by ID114514** [comment]
> 麻了 .. 奇怪的格式增加了!

麻了...刚开始用的这个json还是显示导入成功...

**Comment by ID114514** [comment]
而且貌似绑定命令仅仅显示信息，，使用：“卡池查询，进度”  命令都会直接显示凭证过期，，

**Comment by yuyumoko** [comment]
因为不能使用反馈的链接了  必须是抽卡页面那个历史记录的链接

**Comment by ID114514** [comment]
> 因为不能使用反馈的链接了 必须是抽卡页面那个历史记录的链接

惊了！原来问题是出现在这个上面。。话说这个项目能进网页截图吗，自动生成图片到群聊内

**Comment by yuyumoko** [comment]
不行

**Comment by ID114514** [comment]
> 不行

那好吧，不过这样也够用了，感谢大佬

**Comment by ID114514** [comment]
现在还有个疑问，就是网页，我clone到本地了，那个host行我是应该填公网地址吗

**Comment by yuyumoko** [comment]
> 现在还有个疑问，就是网页，我clone到本地了，那个host行我是应该填公网地址吗

是的

**Comment by ID114514** [comment]
> > 现在还有个疑问，就是网页，我clone到本地了，那个host行我是应该填公网地址吗
> 
> 是的

然后应该是端口那个是保留原有吗？
我的公网地址XXXXX：7711

**Comment by ID114514** [comment]
https://XXXXX:7711

**Comment by yuyumoko** [comment]
> 

就是你hoshino启动的那个地址必须是0.0.0.0:7711 这种

**Comment by ID114514** [comment]
hoshino与CQ反向的那个网址吗

**Comment by yuyumoko** [comment]
你hoshino启动的时候 最下面不是有个地址 ..

**Comment by ID114514** [comment]
> 你hoshino启动的时候 最下面不是有个地址 ..

哦哦，了解了！填完后直接 yarn start 就算成功了吧应该

**Comment by yuyumoko** [comment]
对 可以

**Comment by ID114514** [comment]
> 对 可以

然后配置文件内 gacha_analyzer_webs 填写的网址直接复制 genshin-gacha-analyzer 这个项目推荐网址的还是？

**Comment by yuyumoko** [comment]
那个配置的网址就是你服务器的公网地址 和 genshin-gacha-analyzer 的端口

**Comment by ID114514** [comment]
所以保持默认就行了吗，或者我应该如何更改它

**Comment by yuyumoko** [comment]
我觉得你应该试试

**Comment by ID114514** [comment]
> 我觉得你应该试试

OK

**Comment by ID114514** [comment]
输入命令后 他返回了一个网站，但网站内是空的，依然提示需要上传xlsx......

**Comment by yuyumoko** [comment]
那可能就是获取的文件失败了  说明page那边没填对地址

**Comment by ID114514** [comment]
> 那可能就是获取的文件失败了 说明page那边没填对地址

公网地址那一栏吗，是按照hoshino启动后 最后一栏显示的地址填入的啊....

**Comment by yuyumoko** [comment]
那你可以F12 看看你获取的那个文件是不是能直接访问

**Comment by ID114514** [comment]
> 那你可以F12 看看你获取的那个文件是不是能直接访问

估摸着应该是传文件的原因把，我能不能直接把文件放目录里头呢？

**Comment by yuyumoko** [comment]
那是自动生成的.. 别直接放

**Comment by ID114514** [comment]
> 那是自动生成的.. 别直接放

......那又回到开始的传文件问题上了，还是期待大佬复刻版把（泪
