### ISSUE TITLE
原神公告#2160无法查看

### ISSUE THREAD

**Issue by chingkingm** [pcrbot/erinilis-modules#11]
公告 _2160 游戏更新修复与优化说明（新增已知问题）_ 查看不了。
<details>
<summary>error</summary>
<pre>
[2021-04-15 11:51:30,339 egenshin] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when main handling message -1512582835.
[2021-04-15 11:51:30,340 egenshin] ERROR: <ActionFailed, retcode=100>
Traceback (most recent call last):
  File "G:\GenshinTools\HoshinoBot\hoshino\service.py", line 189, in wrapper
    return await func(self.bot, ctx)
  File "G:\GenshinTools\HoshinoBot\hoshino\modules\egenshin\__init__.py", line 33, in main
    await _bot.send(ctx, await ann().ann_detail_msg(int(keyword)))
  File "C:\Users\123\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 256, in send
    return await self.send_msg(**params)
  File "C:\Users\123\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 223, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\123\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Users\123\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 161, in call_action
    return _handle_api_result(
  File "C:\Users\123\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 51, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed: <ActionFailed, retcode=100>
</pre>
</details>
go-cqhttp报的是

`[WARNING]: 群消息发送失败: 账号可能被风控.`

**Comment by yuyumoko** [comment]
我刚刚测试了下, 是可以的, 可能真被风控了

**Comment by chingkingm** [comment]
啊这。。谢谢
