### ISSUE TITLE
原神深渊配队报错

### ISSUE THREAD

**Issue by kendajiwaimai** [pcrbot/erinilis-modules#121]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\egenshin\spiral_abyss\__init__.py", line 77, in main
    raise e
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\egenshin\spiral_abyss\__init__.py", line 68, in main
    img = await recommend_team(floor=keyword, avatars=user_info.data.avatars)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\egenshin\spiral_abyss\match_teams.py", line 58, in recommend_team
    raise Exception('配队失败,匹配不到对应阵容')
Exception: 配队失败,匹配不到对应阵容

**Comment by 3273576540** [comment]
深渊榜一封就没更新了，而且现在不绑cookie查不全角色信息
