### ISSUE TITLE
eqa:问题里包含图片bot不会回应,但删除回答提示成功

### ISSUE THREAD

**Issue by gracale** [pcrbot/erinilis-modules#13]
环境win10,go-cqhttp-v1.0.0-beta3,Hoshino v2.0-RIP
问文字答文字,问文字答图片均无问题.
别的插件都关闭了,大佬的代码我看不懂,下面是log.

PS E:\IdeaProjects\HoshinoBot-master> py -3.8 run.py 
ujson module not found, using json 
[2021-04-28 23:28:02,726 config] WARNING: Not found config of "eqa" 
[2021-04-28 23:28:03,160 nonebot] INFO: Succeeded to import "hoshino.modules.eqa.util" 
[2021-04-28 23:28:03,161 nonebot] INFO: Running on 127.0.0.1:2333 Running on http://127.0.0.1:2333 (CTRL + C to quit) 
[2021-04-28 23:28:03,163 nonebot] INFO: Scheduler started 
[2021-04-28 23:28:03,164] Running on 127.0.0.1:2333 over http (CTRL + C to quit) 
[2021-04-28 23:28:05,422] 127.0.0.1:60115 GET /ws 1.1 101 - 1002 
[2021-04-28 23:28:10,091 nonebot] INFO: Self: 2228640919, Message 1967456494 from 管理员@[群:群号]: '大家问[CQ:image,file=f635cf2624998394e85399feac8c3884.image,url=http://gchat.qpic.cn/gchatpic_new/管理员/群号-3058873044-F635CF2624998394E85399FEAC8C3884/0?ter m=3]回答好' 
[2021-04-28 23:28:18,897 eqa] ERROR: <class 'KeyError'> occured when eqa_main handling message -1689558590. 
[2021-04-28 23:28:18,912 eqa] ERROR: 'cmd_head_str' Traceback (most recent call last):   File "E:\IdeaProjects\HoshinoBot-master\hoshino\service.py", line 189, in wrapper     return await func(self.bot, ctx)   File "E:\IdeaProjects\HoshinoBot-master\hoshino\modules\eqa\__init__.py", line 50, in eqa_main     ans = await answer(ctx)   File "E:\IdeaProjects\HoshinoBot-master\hoshino\modules\eqa\__init__.py", line 176, in answer     if _msg['type'] == 'text' and _msg['data']['text'][:1] == config['str']['cmd_head_str']: KeyError: 'cmd_head_str' 
[2021-04-28 23:28:18,913 nonebot] INFO: Self: 2228640919, Message -1689558590 from 管理员@[群:群号]: '[CQ:image,file=f635cf2624998394e85399feac8c3884.image,url=http://gchat.qpic.cn/gchatpic_new/管理员/群号-2981868856-F635CF2624998394E85399FEAC8C3884/0?term=3]'  
[2021-04-28 23:28:25,884 eqa] ERROR: <class 'KeyError'> occured when eqa_main handling message -330542764. 
[2021-04-28 23:28:25,886 eqa] ERROR: 'cmd_head_str' Traceback (most recent call last):   File "E:\IdeaProjects\HoshinoBot-master\hoshino\service.py", line 189, in wrapper     return await func(self.bot, ctx)   File "E:\IdeaProjects\HoshinoBot-master\hoshino\modules\eqa\__init__.py", line 50, in eqa_main     ans = await answer(ctx)   File "E:\IdeaProjects\HoshinoBot-master\hoshino\modules\eqa\__init__.py", line 176, in answer     if _msg['type'] == 'text' and _msg['data']['text'][:1] == config['str']['cmd_head_str']: KeyError: 'cmd_head_str' 
[2021-04-28 23:28:25,888 nonebot] INFO: Self: 2228640919, Message -330542764 from 群友@[群:群号]: '[CQ:image,file=f635cf2624998394e85399feac8c3884.image,url=http://gchat.qpic.cn/gchatpic_new/群友/群号-2980251728-F635CF2624998394E85399FEAC8C3884/0?term=3]'

**Comment by yuyumoko** [comment]
我刚刚测试了下 是可以的，这个报错来自配置文件 `config.yaml` 中的 `cmd_head_str` 字段错误。可以检查一下

**Comment by gracale** [comment]
> 我刚刚测试了下 是可以的，这个报错来自配置文件 `config.yaml` 中的 `cmd_head_str` 字段错误。可以检查一下

尴尬，从0.0.7升级到0.0.8我只替换了init和util文件，config文件还是0.0.7的没有 cmd_head_str字段，添上就没问题了，打扰艾琳佬了。
