### ISSUE TITLE
服务器崩了一次，然后拉了最新的hoshino，就报错了

### ISSUE THREAD

**Issue by davidelectricfree** [pcrbot/erinilis-modules#146]
服务器崩了一次，然后拉了最新的hoshino，就报错了。

[2022-05-23 00:47:52,893 nonebot] ERROR: Failed to import "hoshino.modules.egenshin.achievement", error: cannot import name 'Message' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,893 nonebot] ERROR: cannot import name 'Message' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
Traceback (most recent call last):
  File "C:\python3.8\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\python3.8\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\GenshinBot\HoshinoBot\hoshino\modules\egenshin\achievement\__init__.py", line 3, in <module>
    from hoshino import Message, MessageSegment, Service, priv
ImportError: cannot import name 'Message' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,896 nonebot] ERROR: Failed to import "hoshino.modules.egenshin.ann", error: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,897 nonebot] ERROR: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
Traceback (most recent call last):
  File "C:\python3.8\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\python3.8\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\GenshinBot\HoshinoBot\hoshino\modules\egenshin\ann\__init__.py", line 1, in <module>
    from hoshino import Service, priv, MessageSegment
ImportError: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,898 nonebot] INFO: Succeeded to import "hoshino.modules.egenshin.baidu_ocr"
[2022-05-23 00:47:52,899 nonebot] ERROR: Failed to import "hoshino.modules.egenshin.daily_note", error: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,900 nonebot] ERROR: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
Traceback (most recent call last):
  File "C:\python3.8\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\python3.8\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\GenshinBot\HoshinoBot\hoshino\modules\egenshin\daily_note\__init__.py", line 3, in <module>
    from hoshino import MessageSegment, Service, priv
ImportError: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,902 nonebot] ERROR: Failed to import "hoshino.modules.egenshin.gacha", error: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,902 nonebot] ERROR: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
Traceback (most recent call last):
  File "C:\python3.8\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\python3.8\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\GenshinBot\HoshinoBot\hoshino\modules\egenshin\gacha\__init__.py", line 2, in <module>
    from hoshino import Service, priv, MessageSegment
ImportError: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,904 nonebot] ERROR: Failed to import "hoshino.modules.egenshin.guess_voice", error: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,906 nonebot] ERROR: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
Traceback (most recent call last):
  File "C:\python3.8\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\python3.8\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\GenshinBot\HoshinoBot\hoshino\modules\egenshin\guess_voice\__init__.py", line 4, in <module>
    from hoshino import Service, MessageSegment, priv
ImportError: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,910 nonebot] INFO: Succeeded to import "hoshino.modules.egenshin.imghandler"
[2022-05-23 00:47:52,911 nonebot] INFO: Succeeded to import "hoshino.modules.egenshin.material"
[2022-05-23 00:47:52,913 nonebot] ERROR: Failed to import "hoshino.modules.egenshin.player_info", error: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,913 nonebot] ERROR: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
Traceback (most recent call last):
  File "C:\python3.8\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\python3.8\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\GenshinBot\HoshinoBot\hoshino\modules\egenshin\player_info\__init__.py", line 1, in <module>
    from hoshino import MessageSegment, Service, priv
ImportError: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,915 nonebot] ERROR: Failed to import "hoshino.modules.egenshin.spiral_abyss", error: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
[2022-05-23 00:47:52,917 nonebot] ERROR: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)
Traceback (most recent call last):
  File "C:\python3.8\lib\site-packages\nonebot\plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\python3.8\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\GenshinBot\HoshinoBot\hoshino\modules\egenshin\spiral_abyss\__init__.py", line 2, in <module>
    from hoshino import Service, priv, MessageSegment
ImportError: cannot import name 'MessageSegment' from 'hoshino' (C:\GenshinBot\HoshinoBot\hoshino\__init__.py)

**Comment by chingkingm** [comment]
咖啡佬改了Hoshino结构https://github.com/Ice-Cirno/HoshinoBot/commit/fb630760a88b4590c076d7b737e7d98eb664d76a
等更新吧，或者暂时手动回退Hoshino到https://github.com/Ice-Cirno/HoshinoBot/commit/fb630760a88b4590c076d7b737e7d98eb664d76a 之前

**Comment by davidelectricfree** [comment]
> 咖啡佬改了Hoshino结构[Ice-Cirno/HoshinoBot@fb63076](https://github.com/Ice-Cirno/HoshinoBot/commit/fb630760a88b4590c076d7b737e7d98eb664d76a) 等更新吧，或者暂时手动回退Hoshino到[Ice-Cirno/HoshinoBot@fb63076](https://github.com/Ice-Cirno/HoshinoBot/commit/fb630760a88b4590c076d7b737e7d98eb664d76a) 之前

感谢解答，机器人插件有点多，才搞好，然后再退回去我担心依赖或者其他东西出问题，就不退了，暂时把这个插件禁用了。

**Comment by davidelectricfree** [comment]
> 咖啡佬改了Hoshino结构[Ice-Cirno/HoshinoBot@fb63076](https://github.com/Ice-Cirno/HoshinoBot/commit/fb630760a88b4590c076d7b737e7d98eb664d76a) 等更新吧，或者暂时手动回退Hoshino到[Ice-Cirno/HoshinoBot@fb63076](https://github.com/Ice-Cirno/HoshinoBot/commit/fb630760a88b4590c076d7b737e7d98eb664d76a) 之前

似乎最新的更新已经解决了，十分感谢。
