### ISSUE TITLE
Cookie耗尽时，未能正常返回提示信息报错

### ISSUE THREAD

**Issue by NepPure** [pcrbot/erinilis-modules#32]
https://github.com/pcrbot/erinilis-modules/blob/d58788e39a950621ba25eff67bae4f5d35ee7e19/egenshin/player_info/query.py#L40

```log
[2021-08-13 10:31:46,904 原神UID查询] ERROR: list index out of range
Traceback (most recent call last):
  File "D:\server\XCW\hoshino\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "D:\server\XCW\hoshino\hoshino\modules\egenshin\player_info\__init__.py", line 50, in main
    raw_data = await query.info(uid=uid)
  File "D:\server\XCW\hoshino\hoshino\modules\egenshin\player_info\query.py", line 89, in info
    return await request_data(uid)
  File "D:\server\XCW\hoshino\hoshino\modules\egenshin\player_info\query.py", line 40, in request_data
    cookie = cookies[config.use_cookie_index]
IndexError: list index out of range
```

**Comment by NepPure** [comment]
还有就是，对于一个uid的重复查询是不是可以考虑用一个Cookie

**Comment by yuyumoko** [comment]
我查了下 就算是重复的uid也不能使用重复查询的cookie,  这cookie耗尽报错我还没遇到过 , 待我之后遇到再修复
