### ISSUE TITLE
深渊配队无合适角色时未能正确返回异常信息

### ISSUE THREAD

**Issue by NepPure** [pcrbot/erinilis-modules#34]
![image](https://user-images.githubusercontent.com/12379907/129647195-3d8c8b10-4d63-4b49-b43b-1bbca06a11b8.png)

返回了异常编码，没有返回抛出的文字异常

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/129673725-8fc89a13-ee05-4c65-a2be-34a5f7c24b68.png)

**Comment by NepPure** [comment]
```
[2021-08-17 14:19:36,990 原神深渊速查] ERROR: <class 'json.decoder.JSONDecodeError'> occured when main handling message 523109215.
[2021-08-17 14:19:36,991 原神深渊速查] ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\server\XCW\hoshino\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "D:\server\XCW\hoshino\hoshino\modules\egenshin\spiral_abyss\__init__.py", line 50, in main
    img = await abyss_use_teams(floor=keyword)
  File "D:\server\XCW\hoshino\hoshino\modules\egenshin\util.py", line 125, in wrapped
    data['value'] = await func(*args, **kw)
  File "D:\server\XCW\hoshino\hoshino\modules\egenshin\spiral_abyss\query.py", line 108, in abyss_use_teams
    data = await get_abyss_data(floor=floor)
  File "D:\server\XCW\hoshino\hoshino\modules\egenshin\util.py", line 125, in wrapped
    data['value'] = await func(*args, **kw)
  File "D:\server\XCW\hoshino\hoshino\modules\egenshin\spiral_abyss\query.py", line 75, in get_abyss_data
    json_data = await res.json(object_hook=Dict)
  File "D:\server\XCW\hoshino\hoshino\aiorequests.py", line 57, in json
    return await run_sync_func(self.raw_response.json, **kwargs)
  File "D:\server\XCW\hoshino\hoshino\aiorequests.py", line 10, in run_sync_func
    return await asyncio.get_event_loop().run_in_executor(
  File "D:\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Programs\Python\Python38\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Programs\Python\Python38\lib\json\__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "D:\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

第二张图好像是 数据源出问题了？

**Comment by yuyumoko** [comment]
> ```
> [2021-08-17 14:19:36,990 原神深渊速查] ERROR: <class 'json.decoder.JSONDecodeError'> occured when main handling message 523109215.
> [2021-08-17 14:19:36,991 原神深渊速查] ERROR: Expecting value: line 1 column 1 (char 0)
> Traceback (most recent call last):
>   File "D:\server\XCW\hoshino\hoshino\msghandler.py", line 28, in handle_message
>     await sf.func(bot, event)
>   File "D:\server\XCW\hoshino\hoshino\modules\egenshin\spiral_abyss\__init__.py", line 50, in main
>     img = await abyss_use_teams(floor=keyword)
>   File "D:\server\XCW\hoshino\hoshino\modules\egenshin\util.py", line 125, in wrapped
>     data['value'] = await func(*args, **kw)
>   File "D:\server\XCW\hoshino\hoshino\modules\egenshin\spiral_abyss\query.py", line 108, in abyss_use_teams
>     data = await get_abyss_data(floor=floor)
>   File "D:\server\XCW\hoshino\hoshino\modules\egenshin\util.py", line 125, in wrapped
>     data['value'] = await func(*args, **kw)
>   File "D:\server\XCW\hoshino\hoshino\modules\egenshin\spiral_abyss\query.py", line 75, in get_abyss_data
>     json_data = await res.json(object_hook=Dict)
>   File "D:\server\XCW\hoshino\hoshino\aiorequests.py", line 57, in json
>     return await run_sync_func(self.raw_response.json, **kwargs)
>   File "D:\server\XCW\hoshino\hoshino\aiorequests.py", line 10, in run_sync_func
>     return await asyncio.get_event_loop().run_in_executor(
>   File "D:\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "D:\Programs\Python\Python38\lib\site-packages\requests\models.py", line 900, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "D:\Programs\Python\Python38\lib\json\__init__.py", line 370, in loads
>     return cls(**kw).decode(s)
>   File "D:\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "D:\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> 第二张图好像是 数据源出问题了？

你这重启一下就好 获取失败了

**Comment by NepPure** [comment]
重启一下确实好了
