### ISSUE TITLE
缺一张埃洛伊的图

### ISSUE THREAD

**Issue by NepPure** [pcrbot/erinilis-modules#41]
```
[2021-09-03 09:11:03,924 原神UID查询] ERROR: [Errno 2] No such file or directory: 'D:\\server\\XCW\\hoshino\\hoshino\\modules\\egenshin\\assets\\chara_card\\10000062.png'
Traceback (most recent call last):
  File "D:\server\XCW\hoshino\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "D:\server\XCW\hoshino\hoshino\modules\egenshin\player_info\__init__.py", line 88, in main
    im = await info_card.draw_info_card(uid=uid,
  File "D:\server\XCW\hoshino\hoshino\modules\egenshin\player_info\info_card.py", line 130, in draw_info_card
    card = await avatar_card(chara['id'], chara["level"], chara["actived_constellation_num"], chara["fetter"])
  File "D:\server\XCW\hoshino\hoshino\modules\egenshin\player_info\info_card.py", line 35, in avatar_card
    card = Image.open(os.path.join(CHARA_CARD, f'{avatar_id}.png'))
  File "D:\Programs\Python\Python38\lib\site-packages\PIL\Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\server\\XCW\\hoshino\\hoshino\\modules\\egenshin\\assets\\chara_card\\10000062.png'
```

**Comment by yuyumoko** [comment]
麻了..全靠issues提醒还行

**Comment by NepPure** [comment]
Python苦逼选手就多帮大佬测测 😋
