### ISSUE TITLE
无法导入原神深渊模块

### ISSUE THREAD

**Issue by chingkingm** [pcrbot/erinilis-modules#51]
<details><summary>报错为：</summary>

`[2021-09-20 09:33:18,368 nonebot] ERROR: Failed to import "hoshino.modules.egenshin.spiral_abyss", error: '2.1'
[2021-09-20 09:33:18,368 nonebot] ERROR: '2.1'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 274, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Genshin\HoshinoBot\hoshino\modules\egenshin\spiral_abyss\__init__.py", line 3, in <module>
    from .query import abyss_use_probability, abyss_use_teams
  File "C:\Genshin\HoshinoBot\hoshino\modules\egenshin\spiral_abyss\query.py", line 28, in <module>
    enemies: dict = json.loads(f.read(), object_hook=Dict)['2.1']
KeyError: '2.1'`

</details>

![Snipaste_2021-09-20_09-43-44](https://user-images.githubusercontent.com/17588900/133950480-603d3d52-ffa7-464f-8e53-dca3fbf70dbb.png)

**Comment by yuyumoko** [comment]
你确定你更新了 [assets](https://github.com/pcrbot/erinilis-modules/blob/master/egenshin/assets/spiral_abyss/enemies.json#L2) 了吗
