### ISSUE TITLE
测试报错了

### ISSUE THREAD

**Issue by jkmiku** [pcrbot/erinilis-modules#8]
这是报错的LOG
[2021-02-18 20:25:41,089 anti-holo] INFO: Message -1016756221 triggered anti_holo by KeywordTrigger.
pixiv refresh cache..
[2021-02-18 20:25:42,951 epixiv] ERROR: <class 'pixivpy3.utils.PixivError'> occured when epixiv_main handling message 762046767.
[2021-02-18 20:25:42,951 epixiv] ERROR: Authentication required! Call login() or set_auth() first!
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\go-cqhttp\HoshinoBot\hoshino\service.py", line 189, in wrapper
    return await func(self.bot, ctx)
  File "C:\Users\Administrator\Desktop\go-cqhttp\HoshinoBot\hoshino\modules\epixiv\__init__.py", line 44, in epixiv_main
    keyword = await search(ctx, footer[-1] if footer else keyword)
  File "C:\Users\Administrator\Desktop\go-cqhttp\HoshinoBot\hoshino\modules\epixiv\__init__.py", line 102, in search
    illusts = await epixiv.search(keyword, search_sort_num=rules.search_sort_num, is_r18=bool(is_r18))
  File "C:\Users\Administrator\Desktop\go-cqhttp\HoshinoBot\hoshino\modules\epixiv\pixiv.py", line 109, in search
    res = self.search_illust(keyword)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pixivpy3\aapi.py", line 278, in search_illust
    r = self.no_auth_requests_call('GET', url, params=params, req_auth=req_auth)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pixivpy3\aapi.py", line 44, in no_auth_requests_call
    self.require_auth()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pixivpy3\api.py", line 51, in require_auth
    raise PixivError('Authentication required! Call login() or set_auth() first!')
pixivpy3.utils.PixivError: Authentication required! Call login() or set_auth() first!

**Comment by yuyumoko** [comment]
#7
