### ISSUE TITLE
报错：Failed to import "hoshino.modules.epixiv.download", error: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by CXY-YSL** [pcrbot/erinilis-modules#98]
[2021-12-04 01:05:46,225 nonebot] ERROR: Failed to import "hoshino.modules.epixiv.download", error: Expecting value: line 1 column 1 (char 0)
[2021-12-04 01:05:46,228 nonebot] ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 274, in load_plugin
    module = importlib.import_module(module_path)
  File "D:\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\BaiduNetdiskDownload\HoshinoBot-2.0-RIP\HoshinoBot\hoshino\modules\epixiv\__init__.py", line 22, in <module>
    epixiv = pixiv.epixiv(
  File "D:\BaiduNetdiskDownload\HoshinoBot-2.0-RIP\HoshinoBot\hoshino\modules\epixiv\pixiv.py", line 94, in __init__
    self.require_appapi_hosts()
  File "D:\Programs\Python\Python38\lib\site-packages\pixivpy3\bapi.py", line 39, in require_appapi_hosts
    self.hosts = "https://" + response.json()['Answer'][0]['data']
  File "D:\Programs\Python\Python38\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yuyumoko** [comment]
年久失修 而且发色图很可能会导致q号被封 ,, 建议别用了 我也去删一下了
