### ISSUE TITLE
关于原神实时便笺的提醒

### ISSUE THREAD

**Issue by Nuevo009** [pcrbot/erinilis-modules#99]
最新的commit，开启 yss 提醒
```
[2021-12-04 15:26:00,258 原神实时便笺] ERROR: 'Daily_Note' object has no attribute 'uid'
Traceback (most recent call last):
  File "/home/ubuntu/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/home/ubuntu/HoshinoBot/hoshino/modules/egenshin/daily_note/__init__.py", line 51, in main
    await bot.finish(ev, await dn.remind(once_remind=once_remind))
  File "/home/ubuntu/HoshinoBot/hoshino/modules/egenshin/daily_note/main.py", line 70, in remind
    db_key = self.get_remind_key()
  File "/home/ubuntu/HoshinoBot/hoshino/modules/egenshin/daily_note/main.py", line 62, in get_remind_key
    return '%s_%s' % (self.qid, self.uid)
AttributeError: 'Daily_Note' object has no attribute 'uid'
```

revert [commit bc6fdcad](https://github.com/pcrbot/erinilis-modules/commit/bc6fdcad0e014338aab09a9142a27a915a656bc4) 解决这一问题

**Comment by Eternity-luo** [comment]
Traceback (most recent call last):  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message    await service_func.func(bot, event)  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\egenshin\daily_note\__init__.py", line 55, in main    await bot.finish(ev, await dn.remind(once_remind=once_remind))  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\egenshin\daily_note\main.py", line 70, in remind    db_key = self.get_remind_key()  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\egenshin\daily_note\main.py", line 62, in get_remind_key    return '%s_%s' % (self.qid, self.uid)AttributeError: 'Daily_Note' object has no attribute 'uid'
